version: '3.4'
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  aspnetcore:
    container_name: quick-refs-server-web
    image: ghcr.io/pb10005/quick-refs-server:master
    environment:
      - REDIS_CONNECTION=redis:6379
      - POSTGRES_CONNECTION=Host=postgres;Port=5432;UserId=username;Password=password;Database=database
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - redis
      - migration
    restart: always
  migration:
    container_name: quick-refs-server-migration
    image: ghcr.io/pb10005/quick-refs-server-migration:master
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=username
      - POSTGRES_DATABASE=database
      - PGPASSWORD=password
    depends_on:
      - postgres